kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: efs-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: efs-plugin
          image: amazon/aws-efs-csi-driver:master
          imagePullPolicy: Always
